version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - vectordb

  vectordb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
